### PR TITLE
Add jabber.el support

### PR DESCRIPTION
**Pull request by ssbb**
It is strange that the support for this has not happened. But now there is! :)

### CODE REVIEW

**Comment by kuanyui** [comment]
Thanks, but I've never use this package so I just can fix some faces that hard to see, but I still cannot ensure what these faces exactly looking in interface. May you willing to post a screenshot for this package to let me improve it?

**Comment by ssbb** [comment]
Screenshots for roster and chat views: http://drp.io/a/Jt/qEM/-/-

**Comment by kuanyui** [comment]
I just merge your PR and modified it. Take a look of the latest master branch to see if these modifications satisfied you :)

**Comment by ssbb** [comment]
Yes, thats great! Thanks!

**Pull request closed without merging**
