### PR TITLE
fix: use unspecified instead of nil for background & foreground

### PR DESCRIPTION
**Pull request by Aaronzinhoo**
Was seeing warnings in the *Messages* buffer referring to nil being specified for faces instead of unspecified. Saw these lines were the culprit so thought I would make a quick PR to address.

### CODE REVIEW

**Comment by kuanyui** [comment]
Thanks for point out this warning, but I never seen this before, do you know when (what version of Emacs) did `unspecified` variable (?) in font face become available? I'm just worry about the backward compatibility.

**Comment by Aaronzinhoo** [comment]
Emacs Version: GNU Emacs 29.0.60
OS: macOS Monterey 12.1

I think the keyword has always been around but has not been recommended until recently. Looking at the source code I can see a commit with the `unspecified` keyword from almost 23 years ago [here](https://github.com/emacs-mirror/emacs/blame/6ecb43cedfcce4bb9c60cec33abd2dae6986f052/src/xfaces.c)

**Comment by nverno** [comment]
this breaks for me [emacs v30] - I see 'Symbol's value as variable is void: unspecified'.

**Comment by kuanyui** [comment]
@nverno Hmm.... I tested on `GNU Emacs 28.2`, under GTK GUI and `-nw` and both of them are workable... 

@Aaronzinhoo Do you have any clue?

**Comment by Aaronzinhoo** [comment]
I'll look into it when I'm home. Continuing the discussion on #126

**Pull request merged**
