### PR TITLE
Quote unspecified

### LINKED ISSUE #126: `unspecified` symbol is void
related to #124

I'm getting error  'Symbol's value as variable is void: unspecified'. 

Not sure if  the symbol should be quoted?

On emacs v30

### PR DESCRIPTION
**Pull request by dakra**
Fix #126

In moe-light/dark unspecified was already quoted everywhere
but the quotes were missing in the main moe-themes.el file.

### CODE REVIEW

**Comment by kuanyui** [comment]
Ok let us try it and see if any user complain XD

**Comment by kuanyui** [comment]
In `custom-theme-set-faces`, all `unspecified` are not quoted, so I'm very confused and donno if this is a special variable or keyword in the scope of  `custom-theme-set-faces`.

**Comment by dakra** [comment]
> In custom-theme-set-faces, all unspecified are not quoted

From a quick look they are. They're quoted from the outer list.
so e.g.
```
   `(org-agenda-done ((,class (:foreground ,green-2 :background unspecified))))
```
everything that doesn't have a `,` prefix is read literal and not interpreted.

**Comment by Aaronzinhoo** [comment]
That is right, completely slipped my mind... thanks for catching this. @dakra

**Pull request merged**
